### ISSUE TITLE
It might be better to recommend the DjangoCMS installer

### ISSUE THREAD

**Issue by topiaruss** [palazzem/cookiecutter-django-cms#19]
On the DjangoCMS site, there is an installer that will normally install up-to-date and tested dependencies.

The current version of this cookie-cutter recipe gave me problems with freetype on OSX Mavericks. While fixing that, I realised that several component version were out of date. 

This highlights one of the deficiencies of the cookiecutter approach - that cross-cutting concerns are lumped together.

**Comment by jab3z** [comment]
Will keep the cookiecutter settings updated with the ones related to django-cms and django.
