### ISSUE TITLE
adding a new contributor

### ISSUE THREAD

**Issue by palazzem** [palazzem/cookiecutter-django-cms#22]
Because I don't have so much time to keep updated this cookiecutter template, I'll add full writing permissions to @jab3z, so that fresh forces can improve the project.

@jab3z please close this issue when you'll receive full write permission for the repository.
Best and fill issues if you need any help :)

(And don't forget to add yourself to the [AUTHORS.rst][1] list)

[1]: https://github.com/palazzem/cookiecutter-django-cms/blob/master/AUTHORS.rst

**Comment by jab3z** [comment]
thanks :)
